# Use root/example as user/password credentials
version: '3.1'

services:
  python:
    build: ./code
    image: heidaralavi/oxygen:1.1
    container_name: oxygen-project
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/app