# Use root/example as user/password credentials
version: '3.1'

services:
  python:
    build: .
    image: heidaralavi/oxygen:1.1
    container_name: oxygen-project
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/app
    ports:
      - 8888:8888
    command: sleep infinity